### ISSUE TITLE
Clipping issue in 'plot.survfit' when providing 'xmax'

### ISSUE THREAD

**Issue by benostendorf** [therneau/survival#102]
When using the `plot.survfit` function, the clipping area of the graph gets too tight when providing a value for `xmax`. 

As an example, compare the output of the two plotting calls:
```
library(survival)

fit1 <- survfit(Surv(futime, fustat) ~ resid.ds, data=ovarian)

## Correct clipping
plot(fit1, mark.time = TRUE) 

## Clipping too tight
plot(fit1, mark.time = TRUE, xmax = 1200) 
```

This becomes more obvious in scenarios with censored cases while y = 1. 
Thanks a lot for looking into it!

**Comment by therneau** [comment]
fixed

**Comment by benostendorf** [comment]
Thanks for looking into it! I'm afraid after updating to the latest version with `devtools::install_github(install_github("therneau/survival")` the issue persists for me with the same code as above.

**Comment by therneau** [comment]
You are going to have to tell me what you mean by "too tight".  The curve looks fine to me.
Start with the unrestricted and then add a vertical line, that's what I see with the xmax version.  

plot(fit1, mark.time = TRUE) 
abline(v=1200)

**Comment by therneau** [comment]
BTW, move this to email (therneau@mayo.edu) if you want faster response.  I keep an archive in github for others, but don't regularly use the system.

**Comment by benostendorf** [comment]
Dear Dr Therneau, 

Thank you very much for looking into this. The clipping issue is very subtle when using the `ovarian` dataset - I’m attaching an image below showing how the line in the group with longer survival is thinner as long as it equals “1” than in the plot without setting the `xmax` parameter. 

I only got aware of this problem because it becomes more obvious in datasets with data that are censored while the curve equals 1 (see the “more obvious example on some of my data). 

Thanks again,
Ben


-------------------------

```R
library(survival)

fit1 <- survfit(Surv(futime, fustat) ~ resid.ds, data=ovarian)

## Correct clipping
plot(fit1, mark.time = TRUE) 

## Clipping too tight
plot(fit1, mark.time = TRUE, xmax = 1200) 
```

**Comment by therneau** [comment]
I see it now.

**Comment by therneau** [comment]
Now fixed.
